server:
  port: 8080

spring:
  profiles:
    active:
    - test 
  mail: 
    host: smtp.gmail.com
    port: 587
    username: jinbrgame153@gmail.com
    password: scae hcjb ivxd wklw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true       
